[package]
name = "blobdb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "=3.0.0-rc.4"
sha2 = "=0.9.8"
itertools = "=0.10.1"
byteorder = "=1.4.3"
arrayref = "=0.3.6"
fs2 = "=0.4.3"
tee_readwrite = "=0.1.0"
hex = "=0.4.3"
tempfile = "=3.2.0"